-- 본문 이미지 첨부 메타데이터 테이블 (PRD F-46 ~ F-51, docs/SCHEMA.md 5장).
--
-- 이 스크립트는 운영(prod) 전용이다. 운영 프로파일은 ddl-auto=validate 라서 테이블을
-- 자동 생성하지 않기 때문이다. 로컬(update)과 테스트(create-drop)는 엔티티에서 자동 생성되므로
-- 실행할 필요가 없다 -- 다만 로컬에서 스키마를 직접 확인하고 싶을 때 실행해도 무해하다.
--
--   psql -h localhost -U postgres -d todolist_db      -f db/add-attachments.sql
--   psql -h localhost -U postgres -d todolist_db_test -f db/add-attachments.sql
--
-- 컬럼 정의는 Attachment 엔티티와 일치해야 한다. 엔티티를 바꾸면 이 파일도 함께 고친다.

CREATE TABLE IF NOT EXISTS attachments (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    todo_id           BIGINT       NULL     REFERENCES todos (id),
    user_id           BIGINT       NOT NULL REFERENCES users (id),
    storage_type      VARCHAR(20)  NOT NULL,
    storage_key       VARCHAR(512) NOT NULL UNIQUE,
    original_filename VARCHAR(255) NOT NULL,
    content_type      VARCHAR(100) NOT NULL,
    file_size         BIGINT       NOT NULL,
    status            VARCHAR(20)  NOT NULL,
    created_at        TIMESTAMP    NOT NULL,
    updated_at        TIMESTAMP    NOT NULL,
    deleted_at        TIMESTAMP    NULL
);

-- 할 일 상세에서 첨부를 모을 때 쓴다.
CREATE INDEX IF NOT EXISTS idx_attachments_todo_deleted
    ON attachments (todo_id, deleted_at);

-- 소유권 검증 조회용 (PRD NF-02).
CREATE INDEX IF NOT EXISTS idx_attachments_user_deleted
    ON attachments (user_id, deleted_at);

-- 고아 파일 정리 배치용 (PRD F-51).
CREATE INDEX IF NOT EXISTS idx_attachments_status_created
    ON attachments (status, created_at);
