-- ==============================================================================
-- todolist_db 전체 스키마 (운영 배포용 정본)
--
-- 생성 방법: Hibernate 스키마 생성 기능으로 엔티티 정의에서 추출했다.
--   jakarta.persistence.schema-generation.scripts.action=create
-- pg_dump 를 쓰지 않은 이유는 RDS 서버(18.3)보다 로컬 클라이언트(17.x)가 낮아
-- pg_dump 가 버전 불일치로 덤프를 거부하기 때문이다.
--
-- 적용 방법 (운영에서는 1회만 수동 실행한다. CLAUDE.md 4장·ROADMAP 11-1)
--   psql -h <RDS엔드포인트> -U postgres -d postgres -c "CREATE DATABASE todolist_db;"
--   psql -h <RDS엔드포인트> -U postgres -d todolist_db -f db/schema.sql
--
-- 운영 프로파일은 ddl-auto=validate 다. 이 스크립트를 적용하지 않으면 기동에 실패한다.
-- 스키마가 바뀌면 이 파일을 갱신하고, 변경분은 별도 마이그레이션 스크립트로 관리한다.
-- ==============================================================================


    create table attachments (
        created_at timestamp(6) not null,
        deleted_at timestamp(6),
        file_size bigint not null,
        id bigint generated by default as identity,
        todo_id bigint,
        updated_at timestamp(6) not null,
        user_id bigint not null,
        status varchar(20) not null check ((status in ('PENDING','UPLOADED','LINKED'))),
        storage_type varchar(20) not null check ((storage_type in ('LOCAL','S3'))),
        content_type varchar(100) not null,
        storage_key varchar(512) not null unique,
        original_filename varchar(255) not null,
        primary key (id)
    );

    create table password_reset_tokens (
        created_at timestamp(6) not null,
        deleted_at timestamp(6),
        expires_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        used_at timestamp(6),
        user_id bigint not null,
        token_hash varchar(64) not null unique,
        primary key (id)
    );

    create table refresh_tokens (
        created_at timestamp(6) not null,
        deleted_at timestamp(6),
        expires_at timestamp(6) not null,
        id bigint generated by default as identity,
        revoked_at timestamp(6),
        updated_at timestamp(6) not null,
        user_id bigint not null,
        token_hash varchar(64) not null unique,
        primary key (id)
    );

    create table todos (
        completed boolean not null,
        due_date date,
        completed_at timestamp(6),
        created_at timestamp(6) not null,
        deleted_at timestamp(6),
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        user_id bigint not null,
        priority varchar(20) not null check ((priority in ('LOW','MEDIUM','HIGH'))),
        title varchar(200) not null,
        content TEXT,
        primary key (id)
    );

    create table users (
        created_at timestamp(6) not null,
        deleted_at timestamp(6),
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        provider varchar(20) not null check ((provider in ('LOCAL','GOOGLE'))),
        nickname varchar(50) not null,
        password varchar(60),
        email varchar(254) not null unique,
        primary key (id)
    );

    create index idx_attachments_todo_deleted 
       on attachments (todo_id, deleted_at);

    create index idx_attachments_user_deleted 
       on attachments (user_id, deleted_at);

    create index idx_attachments_status_created 
       on attachments (status, created_at);

    create index idx_todos_user_deleted 
       on todos (user_id, deleted_at);

    alter table if exists attachments 
       add constraint FKcbli0d2ybr4o26jtyh9xjylld 
       foreign key (todo_id) 
       references todos;

    alter table if exists attachments 
       add constraint FKrap79tymgdjf1c5x4dla3rekl 
       foreign key (user_id) 
       references users;

    alter table if exists password_reset_tokens 
       add constraint FKk3ndxg5xp6v7wd4gjyusp15gq 
       foreign key (user_id) 
       references users;

    alter table if exists refresh_tokens 
       add constraint FK1lih5y2npsf8u5o3vhdb9y0os 
       foreign key (user_id) 
       references users;

    alter table if exists todos 
       add constraint FK9605g76a1dggbvs18f2r80gvu 
       foreign key (user_id) 
       references users;

-- ==============================================================================
-- 함수 기반 인덱스 (수동 관리)
--
-- JPA @Table(indexes=...) 는 컬럼 인덱스만 만들 수 있어 LOWER(title) 같은 표현식
-- 인덱스를 생성하지 못한다. 그래서 위 자동 생성분에 포함되지 않으며 여기서 보강한다.
-- 원본은 db/add-title-index.sql 이고 내용이 같아야 한다 (ROADMAP Phase 4).
-- ==============================================================================
CREATE INDEX IF NOT EXISTS idx_todos_title_lower ON todos (LOWER(title));
